name: stistools
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - numpy>=1.5.1
  - numpydoc
  - astropy>=3.1.1
  - scipy>=0.14
  - sphinx=1.8
  - stsci.tools
  - d2to1
  - stsci.distutils
  - stsci.tools
  - ipython
  - pip:
    - stsci_rtd_theme
    - sphinx_automodapi
